print("\n Resultado esperado: \n")
print("Diario de un Astronauta \n")
print("Fecha: 2024-01-10 \n")
print("Hoy experimentamos con el cultivo de plantas en microgravedad. \n")
print("Mensaje personal: ¡Es increible ver como crecen las lechugas aqui arriba! \n")
print("Fecha: 2024-01-11 \n")
print("Realizamos una caminata espacial para reparar un panel solar. \n")
print("Mensaje personal: Flotar en el espacio nunca deja de asombrarme. \n")